fix issue when in 'pd-queue status', when a intgeration key is throttled
PagerDuty/pdagent pull request #161
Opened 2021-02-04 13:34 UTC by wat-org

when an integration key is throttled, the binary 'pd-queue status' failed with :
```
[root@sensu0103e2 ~]# pd-queue status
Service Key                           Pending   Success  In Error
=================================================================
R0213KMAJD6IKNEZICDCTNAV21Q305U7            0       224         0
R0238CCPZB28FCUNJ81KGJ7CN1S74BFO            0        12         0
R024AH4SBVWQ45NLDFT2Y1XLZ0ANEXCB            0        19         0
R026FK82KQBQRY3W1G2IHLK460HA9DFJ            0       724         0
R026QQMPSL2RYWVM43CH2DA6Z1VXNGGG            0        73         0
R027BDHJ45D1GXPS72BU0NOVC0KUHGMB            0         2         0
R02BG5SWMBYJ1950ZDQUOT3E70LXS7EM         8444        21         0
R02CJE3QIR5AMWA87XE2VPCPU0O8NH3Q            0        42         0
R02GLM3H1AYLLGCN7RKL2N0OR0Q5BGMN            0         7         0
Traceback (most recent call last):
  File "/bin/pd-queue", line 147, in <module>
    main()
  File "/bin/pd-queue", line 135, in main
    args.func(load_agent_config(), parser, args)
  File "/bin/pd-queue", line 123, in _status
    state.get("pending_events", empty_dict).get("count", 0),
AttributeError: 'int' object has no attribute 'get'
```

This pull request fixes the issue, and introduce a new column 'Throttled' in the pd-queue status output, as illustrated below:
```
[root@sensu0103e2 ~]# pd-queue status
Service Key                           Pending   Success  In Error Throttled
===========================================================================
R0213KMAJD6IKNEZICDCTNAV21Q305U7            0       231         0         0
R0238CCPZB28FCUNJ81KGJ7CN1S74BFO            0        12         0         0
R024AH4SBVWQ45NLDFT2Y1XLZ0ANEXCB            0        17         0         0
R025RD4U2BBJZXHUSSV1Q2GK412F71BQ            0         2         0         0
R026FK82KQBQRY3W1G2IHLK460HA9DFJ            0       728         0         0
R026QQMPSL2RYWVM43CH2DA6Z1VXNGGG            0        74         0         0
R027BDHJ45D1GXPS72BU0NOVC0KUHGMB            0         4         0         0
R02BG5SWMBYJ1950ZDQUOT3E70LXS7EM         8170        58         0         0
R02CJE3QIR5AMWA87XE2VPCPU0O8NH3Q            0        44         0         1
R02GLM3H1AYLLGCN7RKL2N0OR0Q5BGMN            0        37         0         0
```

2021-02-11 14:20 UTC, wat-org commented
any news ?

2021-02-16 12:50 UTC, wat-org commented
Is there anybody out there ?

2021-02-16 19:44 UTC, ChezCrawford commented
@wat-org : we're here!  We will have a look at this and get back to you.

2021-02-16 20:26 UTC, blagh requested changes
Hey there, it looks like there is a failing test:

```FILE: unit_tests/test_pdqueue.py
..............F.
======================================================================
FAIL: test_stats (__main__.PDQueueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_tests/test_pdqueue.py", line 825, in test_stats
    expected_stats
AssertionError: {'snapshot': {'svckey1': {'pending_events': {'count': 1,[746 chars]: 2}} != {'snapshot': {'throttled_service_keys_count': 1, 'svckey[762 chars]me'}}
Diff is 2260 characters long. Set self.maxDiff to None to see it.
```

Could you update that test before we approve the changes? Looks like it should be pretty straightforward.

2021-03-02 12:59 UTC, wat-org commented
Thanks for your feedback.
Unit-tests are fixed.
I've update the doc of the function 'get_stats' too.
Let me know,if it is ok now.

NB:
For coherance resaon, I did this change in the unit-test : 
```
-        # also, let's throttle svckey2...
-        q.backoff_info.increment("svckey2")
+        # also, let's throttle svckey1...
+        q.backoff_info.increment("svckey1")
```
I don't dive deep into but it looks like this code doesn't throttle the specified service key...
There might be a bug in the mock somewhere...

2021-03-09 16:46 UTC, wat-org commented
hello,
any news?

2021-03-18 18:39 UTC, wat-org commented
heeeello ?

2021-03-19 17:15 UTC, ChezCrawford approved these changes

2021-03-19 17:16 UTC, blagh approved these changes
Sorry for the delay! Thanks for updating the test

2021-03-19 17:27 UTC, merged

2021-03-20 11:38 UTC, wat-org commented
many thanks team :+1:

2021-03-20 11:40 UTC, wat-org commented
do you plan to build a new version soon?

2021-03-22 17:08 UTC, bzmw commented
Stayed tuned ;)